#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

# Target for the executable
all:

install:
	install -d $(PREFIX)/python
	install -m 644 espa_constants.py $(PREFIX)/python
	install -m 644 espa_logging.py $(PREFIX)/python

clean:

