#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the modules.
#------------------------------------------------------------------------------

all:

install:
	install -d $(PREFIX)/python
	install -m 644 espa_constants.py $(PREFIX)/python
	install -m 644 espa_logging.py $(PREFIX)/python
	install -m 644 metadata_api.py $(PREFIX)/python

clean:

